### PR TITLE
🚜 Rewrite of add-on

### PR DESCRIPTION
**Pull request by frenck**
# Proposed Changes

Major rewrite of the Matrix add-on.

- Migrates base image from the Alpine Python to Debian.
- Replace/upgrade Riot web with Element web
- Upgrade CI to be in line with all other add-ons (including caching, signing and all the good stuff)
- Re-implements NGINX configuration to no longer use LUA for authentication
- Move some files around
- Drop support for 32-bits platforms (armhf, armv7 & i386)

### CODE REVIEW

**Comment by marcelmah** [comment]
Nice to see this gets some TLC!

**Comment by bohtho** [comment]
Any news on the shift to Element Web and this PR?

**Comment by frenck** [comment]
nope

**Comment by bohtho** [comment]
That wasn't meant to sound demanding. I'm about to fork and contribute to another two Hass addons for the first time, but there are things over my head in this PR which I hope somebody else jumps in on. Would be cool to supply a matrix synapse server with all bridges to my family so everybody can use just the Element messenger (although I wonder if it's possible to run the Synapse server non-publicly on my tailnet). Anyway, thanks for all your work put into the Hass ecosystem.

**Comment by frenck** [comment]
> That wasn't meant to sound demanding.

I didn't receive it as such. It was just a short and simple answer 🤷

**Comment by Cooper-Dale** [comment]
Hi, I am not able to login using HA username and password `Attempted to login as @HAuser:xxx.duckdns.org but they do not exist`, does this rewrite solve this problem?

**Pull request closed without merging**
